### PR TITLE
Update `request` to v2.88.2

### PR DESCRIPTION
**Pull request by andrejleitner**
- to at least fix vulnerability mentioned here: https://github.com/closeio/closeio-node/issues/31

### CODE REVIEW

**Comment by andrejleitner** [comment]
cc @taylorbrooks @philfreo

**Comment by andrejleitner** [comment]
Thanks for merging PR @taylorbrooks! Would it be possible to publish new version with the latest changes to `npm`?

**Comment by andrejleitner** [comment]
ping

**Comment by jabuj-amalytix** [comment]
Hello! Is the library still maintained? The PR has been merged three years ago, but the change was never published to NPM. @taylorbrooks

**Pull request merged**
